language: go

go:
  - "1.12.5"

env:
  global:
    - SSH_KEY="id_rsa"
    - GIT_NAME="Kostiantyn Lysenko"
    - GIT_EMAIL="gshaud@gmail.com"
    - SOURCE_DIR="public"
    - DEPLOY_BRANCH="master"

before_install:
  - openssl aes-256-cbc -K $encrypted_a79a3e2fa35f_key -iv $encrypted_a79a3e2fa35f_iv -in travis_id_rsa.enc -out id_rsa -d

install:
  - true
  
before_script:
  - ./scripts/install_hugo.sh

script:
  - hugo

after_success:
 - echo "verydevops.com" > ./public/CNAME
 - ./scripts/deploy.sh
