baseurl = "http://verydevops.com/"
disablePathToLower = false
languageCode = "en-us"
title = "Yet another one DevOps blog"
theme = "hugo-octopress"
canonifyurls = true

# Disqus shortcode
# Disable comments for a specific post by adding "comments: false" in its frontmatter
disqusShortname = "jakshi"

# Number of blog posts displayed in each page
paginate = 10

# Keep it as false please, the css file contains the code for highlighting
pygmentsuseclasses = false

# If nothing is set, then solarized_light is used
# Other styles can be viewed in [http://pygments.org/](http://pygments.org/)
pygmentsstyle = "solarized_dark"

# Highlight shortcode and code fences (```) will be treated similarly
pygmentscodefences = true

# pygments options can be added here
# Hugo supports these pygments options: style, encoding, noclasses, hl_lines, linenos
# for example: pygmentsoptions = "linenos=true"

[permalinks]
post = "/blog/:year-:month-:day-:title/" # change the post URL to look like the old ones

# Make tags and categories work
[indexes]
    tag = "tags"
    category = "categories"

[params]
    # If false, all of the post will appear on front page (and in pagination)
    truncate = true

    # Author's name (this will appear in metadata and under posts)
    author = "Kostiantyn Lysenko"

    # This text appears in the site header under website title
    subtitle = "Ops and DevOps stories"

    # Used in the search engine
    searchEngineURL = "https://www.google.com/search"

    # Text of the "Continue Reading" label. &rarr; == right arrow, but it gets messed up in the string so we will add it to index.html manually
    continueReadingText = "Would you like to know more?"

    # Google analytics code
    googleAnalytics = "google analytics"


    rss = true  # switch to true to enable RSS icon link

    # Set to true to use a text label for RSS instead of an icon
    # This is overwritten by the `rss` setting
    textrss = false

    # Website's default description
    defaultDescription = ""

    # Populate this with your own search keywords - these will appear in the meta tags
    # defaultKeywords = ["keyword1" , "keyword2" , "keyword3" , "keyword4"]

    # Set to true to hide ReadingTime on posts
    disableReadingTime = false

    sidebarMenuEnabled = true

    # Set to true to disable downloading of remote Google fonts
    disableGoogleFonts = false

    github = "https://github.com/jakshi"
    linkedin = "http://ua.linkedin.com/in/konstantinlysenko"
    facebook = "https://www.facebook.com/fjakshi"

[blackfriday]
    hrefTargetBlank = true # open the external links in a new window
    fractions = false

[menu]
  [[menu.main]]
      Name = "Blog"
      URL = "/"
      weight = -10

  [[menu.main]]
      Name = "About me"
      identifier = "about"
      url = "/about/"
      weight = -5
